### PR TITLE
MiniZinc support for regular.

### PR DESCRIPTION
**Pull request by mmcilree**

### CODE REVIEW

**Comment by ciaranm** [comment]
Can you get the nurses test to run automatically as well?

**Comment by mmcilree** [comment]
> Can you get the nurses test to run automatically as well?

Can do but it's relatively slow (like 30s) not sure why...

**Comment by ciaranm** [comment]
> Can do but it's relatively slow (like 30s) not sure why...

Hah, then adding it in might motivate me to benchmark it at some point.

**Comment by mmcilree** [comment]
ok :)

**Pull request merged**
