### PR TITLE
Here's a basic python interface.

### PR DESCRIPTION
**Pull request by mmcilree**
Could you try checking out this branch and doing

```bash
cd python
pip install .
python3 python_test.py
```

I've got this to work on mine after a bit of trial and error but not sure how stable it is.

### CODE REVIEW

**Comment by ciaranm** [comment]
Hrm, this doesn't work for me on Ubuntu. It looks like it's trying to recompile the entirety of the solver, separately, rather than using the already-compiled version?

```
$ pipx install .
  error: subprocess-exited-with-error
  
  × Building wheel for gcspy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [146 lines of output]
...
      [6/229] cd /home/ciaranm/glasgow-constraint-solver/generator/src/generator-build && /usr/bin/cmake -GNinja -S /home/ciaranm/glasgow-constraint-solver/generator/src/generator -B /home/ciaranm/glasgow-constraint-solver/generator/src/generator-build && /usr/bin/cmake -E touch /home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-configure
      FAILED: /home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-configure
      cd /home/ciaranm/glasgow-constraint-solver/generator/src/generator-build && /usr/bin/cmake -GNinja -S /home/ciaranm/glasgow-constraint-solver/generator/src/generator -B /home/ciaranm/glasgow-constraint-solver/generator/src/generator-build && /usr/bin/cmake -E touch /home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-configure
      CMake Error: Error: generator : Ninja
      Does not match the generator used previously: Unix Makefiles
      Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```

**Comment by mmcilree** [comment]
Does it work if you delete the previous /build /generator folders? 

Would it be a problem if it recompiles the solver? - the pip install is meant for people who want to use the gcspy package standalone (e.g. Belgium), so just clone repo and run pip without doing anything else.

**Comment by ciaranm** [comment]
It doesn't: for some reason CMake tries to use `ninja` rather than `make` as its build tool. I guess I could install `ninja`, except we're entering "not very robust" territory here, which worries me.

**Comment by mmcilree** [comment]
Hmmm. scikit-build-core (python build backend) claims it will install ninja if it's not already present.

Can I see the output of `pip -v install .` - ?

**Comment by ciaranm** [comment]
```
$ pipx install -v .
pipx >(setup:860): pipx version is 1.4.3
pipx >(setup:861): Default python interpreter is '/usr/bin/python3'
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: /home/ciaranm/glasgow-constraint-solver/python
creating virtual environment...
pipx >(run_subprocess:168): running /usr/bin/python3 -m venv --without-pip /tmp/tmp2_44e69l
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:168): running /tmp/tmp2_44e69l/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /home/ciaranm/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /tmp/tmp2_44e69l/bin/python --version
determining package name from '/home/ciaranm/glasgow-constraint-solver/python'...
pipx >(run_subprocess:168): running /tmp/tmp2_44e69l/bin/python -m pip list --format=json
pipx >(run_subprocess:168): running /tmp/tmp2_44e69l/bin/python -m pip --no-input install --no-dependencies /home/ciaranm/glasgow-constraint-solver/python
pipx >(run_subprocess:168): running /tmp/tmp2_44e69l/bin/python -m pip list --format=json
pipx >(install_package_no_deps:323): Determined package name: gcspy
pipx >(package_name_from_spec:382): Package name determined in 281.4s
creating virtual environment...
pipx >(run_subprocess:168): running /usr/bin/python3 -m venv --without-pip /home/ciaranm/.local/pipx/venvs/gcspy
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:168): running /home/ciaranm/.local/pipx/venvs/gcspy/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /home/ciaranm/.local/pipx/venvs/gcspy/bin/python --version
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: /home/ciaranm/glasgow-constraint-solver/python
installing gcspy from spec '/home/ciaranm/glasgow-constraint-solver/python'...
pipx >(run_subprocess:168): running /home/ciaranm/.local/pipx/venvs/gcspy/bin/python -m pip --no-input install /home/ciaranm/glasgow-constraint-solver/python
pipx >(subprocess_post_check_handle_pip_error:327): '/home/ciaranm/.local/pipx/venvs/gcspy/bin/python -m pip --no-input install /home/ciaranm/glasgow-constraint-solver/python' failed
pipx >(subprocess_post_check_handle_pip_error:342): Fatal error from pip prevented installation. Full pip output in file:
    /home/ciaranm/.local/pipx/logs/cmd_2024-07-05_17.30.08_pip_errors.log

pipx >(analyze_pip_output:298): pip failed to build package:
    gcspy

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    No such file or directory

pipx >(rmdir:55): removing directory /home/ciaranm/.local/pipx/venvs/gcspy
Error installing gcspy from spec '/home/ciaranm/glasgow-constraint-solver/python'.
```
q
Then in the log file:

```
      -- Performing Test RANGE_V3_ALIGNED_NEW_PROBE - Success
      -- Performing Test RANGE_V3_HAS_FCONCEPTS
      -- Performing Test RANGE_V3_HAS_FCONCEPTS - Success
      -- Configuring done (26.4s)
      -- Generating done (0.1s)
      -- Build files have been written to: /tmp/tmpixbvmns2/build
      *** Building project with Ninja...
      Change Dir: '/tmp/tmpixbvmns2/build'
      
      Run Build Command(s): /tmp/pip-build-env-rml7lcs5/normal/lib/python3.12/site-packages/ninja/data/bin/ninja -v
      [1/229] cd /tmp/tmpixbvmns2/build && /usr/bin/cmake -Dcfgdir= -P /home/ciaranm/glasgow-constraint-solver/generator/tmp/generator-mkdirs.cmake && /usr/bin/cmake -E touch /home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-mkdir
      [2/229] cd /home/ciaranm/glasgow-constraint-solver/generator/src && /usr/bin/cmake -P /home/ciaranm/glasgow-constraint-solver/generator/tmp/generator-gitclone.cmake && /usr/bin/cmake -E touch /home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-download
      -- Avoiding repeated git clone, stamp file is up to date: '/home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-gitclone-lastrun.txt'
      [3/229] /usr/bin/x86_64-linux-gnu-g++  -I/home/ciaranm/glasgow-constraint-solver/. -I/tmp/tmpixbvmns2/build/_deps/catch2-src/src/catch2/.. -I/tmp/tmpixbvmns2/build/_deps/catch2-build/generated-includes -O3 -DNDEBUG -std=c++20 -fPIC -W -Wall -march=native -Wno-restrict -Wno-stringop-overread -Wno-unqualified-std-cast-call -g -g3 -gdwarf-3 -pthread -O3 -ffile-prefix-map=/tmp/tmpixbvmns2/build/_deps/catch2-src/= -MD -MT _deps/catch2-build/src/CMakeFiles/Catch2.dir/catch2/generators/catch_generator_exception.cpp.o -MF _deps/catch2-build/src/CMakeFiles/Catch2.dir/catch2/generators/catch_generator_exception.cpp.o.d -o _deps/catch2-build/src/CMakeFiles/Catch2.dir/catch2/generators/catch_generator_exception.cpp.o -c /tmp/tmpixbvmns2/build/_deps/catch2-src/src/catch2/generators/catch_generator_exception.cpp
      [4/229] cd /home/ciaranm/glasgow-constraint-solver/generator/src/generator && /usr/bin/cmake -Dcan_fetch=YES -P /home/ciaranm/glasgow-constraint-solver/generator/tmp/generator-gitupdate.cmake
      [5/229] cd /tmp/tmpixbvmns2/build && /usr/bin/cmake -E echo_append && /usr/bin/cmake -E touch /home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-patch
      [6/229] cd /home/ciaranm/glasgow-constraint-solver/generator/src/generator-build && /usr/bin/cmake -GNinja -S /home/ciaranm/glasgow-constraint-solver/generator/src/generator -B /home/ciaranm/glasgow-constraint-solver/generator/src/generator-build && /usr/bin/cmake -E touch /home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-configure
      FAILED: /home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-configure
      cd /home/ciaranm/glasgow-constraint-solver/generator/src/generator-build && /usr/bin/cmake -GNinja -S /home/ciaranm/glasgow-constraint-solver/generator/src/generator -B /home/ciaranm/glasgow-constraint-solver/generator/src/generator-build && /usr/bin/cmake -E touch /home/ciaranm/glasgow-constraint-solver/generator/src/generator-stamp/generator-configure
      CMake Error at CMakeLists.txt:6 (project):
        Running
      
         '/tmp/pip-build-env-hymd1jn2/normal/bin/ninja' '--version'
      
        failed with:
      
         No such file or directory
      
      
      -- Configuring incomplete, errors occurred!
```

**Comment by mmcilree** [comment]
If I try it on a fatanode it works from a clean clone of the repository (without installing ninja or anything else first).

If I compile the solver first it breaks in the same way as yours, but then if do

``
rm -rf build generator generated_includes
cd python
pip3 install .
``

it works again. 

Sorry to be a pain, but does it definitely not work even from a fresh clone for you?

**Comment by ciaranm** [comment]
Hrm so this is interesting, it fails in the same way with a fresh clone even on a fatanode for me.

**Comment by mmcilree** [comment]
Argh okay. Yes this is definitely not so robust then. I must have things installed already on my fatanode profile that are magically making it work somehow... hmm...

**Comment by ciaranm** [comment]
OK, if I have `ninja` installed globally, it gets further when using `pipx`:

```
No apps associated with package gcspy or its dependencies. If you are attempting to install a library, pipx should not be used.
Consider using pip or a similar tool instead.
```

But I can't use `pip3` without `venv` on newer Ubuntu. So now I have to work out how `venv` works.

**Comment by ciaranm** [comment]
If I use `venv` and have `ninja` already installed, I can run the tests.

**Comment by ciaranm** [comment]
If I use `venv` and I don't have `ninja` installed, it still seems to work. So, I guess the answer is to always use `venv`?

**Comment by mmcilree** [comment]
Yay, not ideal, but at least it's something for now. 

Can I merge? (it shouldn't mess up any CI stuff)

**Comment by ciaranm** [comment]
Can you check what you're doing to the `In` constraint? Looks half-finished? Other than that, good to merge.

**Comment by mmcilree** [comment]
So the `In` constraint had a very sneaky bug that was causing one of the python tests to fail. 

If I posted `In{x, {y, z}}` for variables `x, y, z` then the `post()` function was immediately calling `In.clone()`, which only called the `In` constructor for `val_vals` rather than `var_vars`, meaning the y, z got lost and the constraint turned into `In{x, {}}` (i.e. immediate contradiction). 

This was wrongly causing no solutions, and sadly, because it was a problem with posting the constraint it couldn't be caught by proof logging (OPB file was just 0 >= 1). 

I fixed it by creating a new constructor that initialises both var_vals and val_vals. A side effect means someone could write a constraint like `In{x, {y, z}, {1, 2, 3}}`... but I don't think there's a problem with this?

**Comment by ciaranm** [comment]
Oh, got it. That new ctor you added should probably be private then?

**Comment by mmcilree** [comment]
`make_unique` can't easily be called with a private constructor apparently https://seanmiddleditch.github.io/enabling-make-unique-with-private-constructors/ 

But maybe it's fine to leave it public - I can't see a semantic problem with creating an In constraint with both variables and integer values together?

**Comment by ciaranm** [comment]
Ok, if the propagator works I guess that's fine. The other option is to
avoid `make_unique` and just use `new` with `unique_ptr`'s ctor.

**Pull request merged**
